import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

// M3: cheatsheets come only from `orca agent-context --json` and carry the orca version they match.
const SCRIPT = new URL('../scripts/gen-orca-cheatsheet.mjs', import.meta.url).pathname;

function fakeOrca(version, commands, { agentContext = true } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fake-orca-'));
  const schema = JSON.stringify({ schemaVersion: 1, commandCount: commands.length, commands });
  fs.writeFileSync(path.join(dir, 'schema.json'), schema);
  const ctx = agentContext ? `cat "${dir}/schema.json"` : 'echo "unknown command: agent-context" >&2; exit 1';
  fs.writeFileSync(path.join(dir, 'orca'),
    `#!/bin/sh\nif [ "$1" = "--version" ]; then echo ${version}; else ${ctx}; fi\n`, { mode: 0o755 });
  return dir;
}
const cmd = (command, extra = {}) => ({
  command, path: command.split(' '), summary: `Do ${command}`, usage: `orca ${command} [--json]`,
  flags: ['help', 'json'], examples: [], notes: [], ...extra,
});

function gen(bin, out, ...args) {
  // null: an empty PATH, so no orca at all (node itself is spawned by absolute path)
  const PATH = bin === null ? fs.mkdtempSync(path.join(os.tmpdir(), 'empty-path-')) : `${bin}:${process.env.PATH}`;
  return spawnSync(process.execPath, [SCRIPT, ...args], {
    encoding: 'utf8', env: { ...process.env, PATH, ORCA_CHEATSHEET_DIR: out },
  });
}

test('generates per-role files with stamp, usage detail and notes; skips platform-only notes', () => {
  const bin = fakeOrca('9.9.9', [
    cmd('orchestration check', {
      usage: 'orca orchestration check [--wait] [--json]\n  --ack: acknowledge the prior batch.',
      notes: ['On Windows PowerShell, quote lists.', 'A bound Run replays the same Delivery until --ack.',
        'Prefer --task-id over raw --payload JSON; PowerShell strips JSON quotes easily.'],
      examples: ['$ orca orchestration check --wait --json'],
    }),
    cmd('terminal wait'),
    cmd('screenshot'),
  ]);
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'cheats-'));
  const r = gen(bin, out);
  assert.equal(r.status, 0, r.stderr);
  const core = fs.readFileSync(path.join(out, 'cheatsheet.md'), 'utf8');
  assert.match(core, /^<!-- generated by gen-orca-cheatsheet\.mjs from orca 9\.9\.9 \(agent-context schema v1\); do not edit/);
  assert.match(core, /### `orca orchestration check`\nDo orchestration check\.\n```\norca orchestration check \[--wait\] \[--json\]\n--ack: acknowledge/);
  assert.match(core, /- A bound Run replays the same Delivery until --ack\./);
  assert.doesNotMatch(core, /quote lists/); // platform-only note dropped
  assert.match(core, /- Prefer --task-id over raw --payload JSON/); // general advice that mentions PowerShell stays
  assert.match(core, /- e\.g\. `orca orchestration check --wait --json`/);
  assert.match(fs.readFileSync(path.join(out, 'cheatsheet-browser.md'), 'utf8'), /### `orca screenshot`/);
  assert.match(fs.readFileSync(path.join(out, 'cheatsheet-producer.md'), 'utf8'), /### `orca terminal wait`/);
  assert.match(r.stdout, /not in orca 9\.9\.9: .*orchestration run-create/); // commands this orca lacks are listed
  assert.equal(gen(bin, out, '--check').status, 0);
  fs.rmSync(bin, { recursive: true });
  fs.rmSync(out, { recursive: true });
});

test('--check reports a stale or missing cheatsheet with the regenerate command', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'cheats-'));
  const old = fakeOrca('1.0.0', [cmd('terminal wait')]);
  assert.equal(gen(old, out).status, 0);
  const now = fakeOrca('1.0.1', [cmd('terminal wait')]);
  const r = gen(now, out, '--check');
  assert.equal(r.status, 1);
  assert.match(r.stdout, /^cheatsheet stale \(orca 1\.0\.1; cheatsheet\.md=1\.0\.0.*\) → node .*gen-orca-cheatsheet\.mjs/);
  fs.rmSync(path.join(out, 'cheatsheet-worker.md'));
  assert.match(gen(old, out, '--check').stdout, /cheatsheet-worker\.md=missing/);
  for (const d of [old, now, out]) fs.rmSync(d, { recursive: true });
});

test('missing orca, an orca without agent-context, and unknown flags fail clearly', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'cheats-'));
  const none = gen(null, out);
  assert.equal(none.status, 2);
  assert.match(none.stderr, /orca is not on PATH/);
  const old = fakeOrca('0.9.0', [], { agentContext: false });
  const check = gen(old, out, '--check');
  assert.equal(check.status, 1);
  assert.match(check.stdout, /has no agent-context: use `orca <command> --help`/); // no dead-end "regenerate"
  assert.equal(gen(old, out).status, 2);
  const typo = gen(old, out, '--chek');
  assert.equal(typo.status, 2);
  assert.match(typo.stderr, /usage: gen-orca-cheatsheet\.mjs/);
  assert.deepEqual(fs.readdirSync(out), []); // nothing written on any failure
  for (const d of [old, out]) fs.rmSync(d, { recursive: true });
});
